
security:
    encoders:
        TicketBundle\Entity\User: 
                 algorithm: bcrypt

    role_hierarchy:
        ROLE_AGENT: ROLE_USER
        ROLE_MANAGER: [ROLE_ADMIN , ROLE_AGENT]
        ROLE_ADMIN: ROLE_MANAGER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN , ROLE_ALLOWED_TO_SWITCH ]
       
    providers:
        user_provider:
            entity:
                class: TicketBundle:User
                property: username

    firewalls:
        staff_area:
            anonymous: ~
            pattern: ^/
            provider: user_provider
            logout: 
                path: /staff/logout
            form_login:
                login_path: login_route
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
            
            
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        
        - { path : ^/staff/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path : ^/staff, roles: IS_AUTHENTICATED_FULLY }
   