
security:
    encoders:
        TicketBundle\Entity\User: 
                 algorithm: bcrypt

    role_hierarchy:
        ROLE_AGENT: ROLE_USER
        ROLE_MANAGER: [ROLE_ADMIN , ROLE_AGENT]
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER , ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
       
    providers:
        user_provider:
            entity:
                class: TicketBundle:User

    firewalls:
        staff_area:
            pattern: ^/staff
            http_basic: ~
            provider: user_provider
            logout: 
                path: /staff/logout
            form_login:
                login_path: /staff/login
                check_path: /staff/login_check
                csrf_provider: security.csrf.token_manager
            anonymous: ~

        main:
            pattern: ^/
            anonymous: ~        
            
 
          
            
            
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        
#        - { path : ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }     
        - { path : ^/staff/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path : ^/staff, roles: IS_AUTHENTICATED_FULLY }
   