services:
    ticket_repository:
        class: TicketBundle\Entity\Repository
        factory: ["@doctrine.orm.entity_manager", getRepository ]
        arguments: [TicketBundle\Entity\Ticket]
# listener maintenance
    maintenance:
        class: TicketBundle\EventListener\Maintenance
        arguments: ["%is_on_maintenance%" ,"%maintenance_template%" ,"@twig" ]
        tags: 
        - { name: kernel.event_listener , event: kernel.request  } 
